#!/usr/bin/env bash
. ./color.sh

echo -e "${GREEN}Installing packages...${NOCOLOR}"
./install_packages.sh
echo -e "${GREEN}DONE${NOCOLOR}"

echo -e "${GREEN}Setting theme...${NOCOLOR}"
./set_theme.sh
echo -e "${GREEN}DONE${NOCOLOR}"

echo -e "${GREEN}Updrading...${NOCOLOR}"
sudo apt-get -y upgrade
echo -e "${GREEN}DONE${NOCOLOR}"

./copy_dotfiles.sh
